// employee-app-with-service/src/app/emp-create/emp-create.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";
import { Employee } from "../model/employee";

@Component({
  selector: "emp-create",
  templateUrl: "./emp-create.component.html",
  styleUrls: ["./emp-create.component.css"],
})
export class EmpCreateComponent implements OnInit {
  
  @Output() close = new EventEmitter();

  constructor() {}

  ngOnInit() {}

  saveData(emp: Employee) {
    this.close.emit(emp);
  }

  cancel() {
    this.close.emit(null);
  }
}

<p style="text-align: center">Create New Employee Data</p>

<form #empForm="ngForm" (submit)="saveData(empForm.value)">
  Emp Id:
  <input class="form-control" ngModel  name='empId' #tempId='ngModel' required pattern='[1-9][0-9]{2}'/>
<div   *ngIf='  tempId.touched && tempId.invalid'>
    <div *ngIf='tempId.errors.required' class='alert alert-danger'>
        Employee Id is required
    </div>
    <div *ngIf='tempId.errors.pattern' class='alert alert-danger'>
        Employee Id should be 3 numeric digits(first digt non-zero)
    </div>
</div>
  Name:
  <input class="form-control" ngModel name='name'  #tname='ngModel'  required minlength='5'/>

  Salary:
  <input type='number' class="form-control" ngModel  name='salary' #tsalary='ngModel' required min='10000' />
  <div   *ngIf='tsalary.touched && tsalary.invalid'>
    <div *ngIf='tsalary.errors.required' class='alert alert-danger'>
        Salary field cannot be empty
    </div>
    <div *ngIf='tsalary.errors.minlength' class='alert alert-danger'>
        Salary should be minimum 10000
    </div>
</div>
  Gender:
  <input class="form-control" ngModel name='gender' #tgender='ngModel' required  pattern='[MF]' />
  <div   *ngIf='tgender.touched && tgender.invalid'>
    <div *ngIf='tgender.errors.required' class='alert alert-danger'>
        gender field cannot be empty
    </div>
    <div *ngIf='tgender.errors.pattern' class='alert alert-danger'>
        Gender should be only M or F
    </div>
</div>
  D O B:
  <input type="date" class="form-control" ngModel  name='dob'  required/>

  <div>
    <button class="btn btn-primary btn-block" type="submit"  [disabled]='empForm.invalid'>Save</button>
    <button class="btn btn-danger btn-block" (click)="cancel()">Cancel</button>
  </div>
  
</form>

// emp-create.tsx
import axios from "axios";
import { FunctionComponent, useState } from "react";
import { useForm } from "react-hook-form";
import Employee from "../model/employee";

interface EmpcreateProps {
    completed:()=>void
}

const Empcreate: FunctionComponent<EmpcreateProps> = (props:EmpcreateProps) => {

    const [message,setMessage] = useState("");
  const {
    register,
    handleSubmit,
    formState: { errors},
  } = useForm<Employee>();

  const [msgStyle,setMsgStyle]=useState({color:'green'})
  const saveData = (data: Employee) => {
   axios.post("http://localhost:8080/employees",data)
   .then(
       (response)=>{setMessage(response.data.message);
        setMsgStyle({color:'green'})
     },
       (error) =>{
           setMessage(error.response.data.message)
           setMsgStyle({color:'red'})
        }
   )
  };

  return (
    <div>
      <h3>Create Employee</h3>
      <form onSubmit={handleSubmit(saveData)}>
        <div className="form-group">
          Employee Id:
          <input
            type="number"
            className="form-control"
            {...register("empid", { required: true })}
          />
        </div>

        { errors.empid ?(<div className='text-danger'>Employee Id required</div>):null    }

        <div className="form-group">
          Name:
          <input
            className="form-control"
            {...register("name", { required: true, minLength: 5 })}
          />
        </div>
        { errors.name && errors.name.type=='required' ?(<div className='text-danger'>Name is required</div>):null    }
        { errors.name && errors.name.type=='minLength' ?(<div className='text-danger'>Name should be minimum 5 chars</div>):null    }
  
        <div className="form-group">
          Salary:
          <input
            type="number"
            className="form-control"
            {...register("salary", { required: true, min: 10000 })}
          />
        </div>
        
        { errors.salary && errors.salary.type=='required' ?(<div className='text-danger'>Salary is required</div>):null    }
        { errors.salary && errors.salary.type=='min' ?(<div className='text-danger'>Salary should be minimum 10000</div>):null    }
  
      
        <div className="form-group">
          Date of Birth:
          <input
            type="date"
            className="form-control"
            {...register("dob", { required: true })}
          />
        </div>
        { errors.dob ?(<div className='text-danger'>Date of Birth required</div>):null    }
        <div>
          <button type="submit" className="btn btn-primary" >
            Save Data
          </button>
          <button className='btn btn-info' onClick={props.completed}>Back To List</button>
        </div>
      </form>
      {message !=''?(<p style={msgStyle}>{message}</p>):null}
    </div>
  );
};

export default Empcreate;
