// emp-list.component.ts
import { Component, OnInit } from "@angular/core";
import { Employee } from "src/model/employee";

@Component({
  selector: "emp-list",
  templateUrl: "./emp-list.component.html",
  styleUrls: ["./emp-list.component.css"],
})
export class EmpListComponent {
  employees: Employee[] = [
    { empId: 100, name: "Suresh", salary: 12000, gender: "M", dob: null },
    { empId: 200, name: "Akhila", salary: 16000, gender: "F", dob: null },
    { empId: 300, name: "Ganesh", salary: 8000, gender: "M", dob: null },
    { empId: 400, name: "Mahesh", salary: 21000, gender: "M", dob: null },
    { empId: 500, name: "Ritesh", salary: 10000, gender: "M", dob: null },
    { empId: 600, name: "Sailesh", salary: 11000, gender: "A", dob: null },
    { empId: 700, name: "Rajani", salary: 10000, gender: "F", dob: null }
  ];

  message: string = null;

  delete(pos: number) {
    this.message = `Employee data with id ${this.employees[pos].empId} deleted`;
    this.employees.splice(pos, 1); // one element at position pos
  }

}

<div class="container">
  <div class="col-lg-6 tablediv">
    <h3 style="text-align: center">Employee List</h3>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>EMP ID</th>
          <th>NAME</th>
          <th>SALARY</th>
          <th>GENDER</th>
          <th>ACTION</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let e of employees; let i = index">
          <td>{{ e.empId }}</td>
          <td>{{ e.name }}</td>
          <td>{{ e.salary }}</td>
          <td [ngSwitch]='e.gender'>
            <span *ngSwitchCase="'M'">Male</span>
            <span *ngSwitchCase="'F'">Female</span>
            <span *ngSwitchDefault>Unknown</span>
          </td>
          <td>
            <button class="btn btn-danger" (click)="delete(i)">Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
    <p *ngIf="message != null"  class="alert alert-danger"   (click)="message = null" >
      {{ message }}
    </p>
  </div>

</div>

// emp-list.tsx
import axios from "axios";
import { useEffect, useState } from "react";
import Employee from "../model/employee";

const EmpList = () => {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [message, setMessage] = useState<string>("");

  useEffect(() => {
    getDateFromServer();
  }, []);

  let getDateFromServer = () => {
    axios.get("http://localhost:8080/employees").then(
      (response) => {
        setEmployees(response.data);
      },
      (error) => {
        //  setMessage(error.response.data.message)
      }
    );
  };

  let deleteData = (eid: number) => {
    axios.delete(`http://localhost:8080/employees/${eid}`).then((response) => {
      setMessage(response.data.message);
      getDateFromServer();
    
      setTimeout( ()=>{ setMessage("") },4000)
    });
  };
  return (
    <div className="container mt-5">
      <div className="col-5">
        <h3 style={{ textAlign: "center",color:'blue' }}>Employee List</h3>
        <table className="table table-striped table-hover">
          <thead>
            <tr>
              <th>EMP ID</th>
              <th>NAME</th>
              <th>SALARY</th>
              <th>D O B</th>
              <th>ACTION</th>
            </tr>
          </thead>
          <tbody>
            {employees.map((e) => {
              return (
                <tr key={e.empid}>
                  <td>{e.empid}</td>
                  <td>{e.name}</td>
                  <td>{e.salary}</td>
                  <td>{e.dob.toLocaleString("en-GB")}</td>
                  <td>
                    <button
                      className="btn btn-danger"
                      onClick={() => deleteData(e.empid)}
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
        {message != "" ? <p className='alert alert-success'>{message}</p> : null}
      </div>
    </div>
  );
};

export default EmpList;
