// routing-app/src/app/emp-list/emp-list.component.ts
import { HttpClient } from "@angular/common/http";
import { Component, OnInit } from "@angular/core";
import { Observable } from "rxjs";
import { Employee } from "../model/employee";
import { EmpService } from "../services/emp.service";

@Component({
  selector: "emp-list",
  templateUrl: "./emp-list.component.html",
  styleUrls: ["./emp-list.component.css"],
})
export class EmpListComponent implements OnInit {
  constructor(private service: EmpService) {}

  ngOnInit(): void {
    this.loadData();
  }

  employees: Employee[];

  message: string = null;

  delete(empid: number) {
    this.service.deleteEmployee(empid).subscribe(
      (resp) => {
        this.loadData();
        this.message = resp.message;
      },
      (response) => {
        this.message=response.error.errorMessage;
      }
    );
  }


  loadData() {
    this.service.getAllEmployees().subscribe(
      (data) => (this.employees = data),
      (response) => (this.message = response.error.errorMessage)
    );
  }
}

<div  class='container'>
  
    <h3 style="text-align: center">Employee List</h3>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>EMP ID</th>
          <th>NAME</th>
          <th>SALARY</th>
          <th>ACTION</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let e of employees">
          <td>{{ e.empid }}</td>
          <td>{{ e.name }}</td>
          <td>{{ e.salary}}</td>
          <td class='btn-group'>
            <a [routerLink]="['/update',e.empid]" class='btn btn-outline-primary mr-2'>Update</a>
            <button class="btn btn-outline-danger" (click)="delete(e.empid)" >Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
    <p *ngIf="message" class="alert alert-danger"  (click)="message = null" >
      {{ message }}
    </p>
 
  </div>

// emp-list.tsx
import axios from "axios";
import { useEffect, useState } from "react";
import Employee from "../model/employee";

const EmpList = () => {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [message, setMessage] = useState<string>("");

  useEffect(() => {
    getDateFromServer();
  }, []);

  let getDateFromServer = () => {
    axios.get("http://localhost:8080/employees").then(
      (response) => {
        setEmployees(response.data);
      },
      (error) => {
        //  setMessage(error.response.data.message)
      }
    );
  };

  let deleteData = (eid: number) => {
    axios.delete(`http://localhost:8080/employees/${eid}`).then((response) => {
      setMessage(response.data.message);
      getDateFromServer();
    
      setTimeout( ()=>{ setMessage("") },4000)
    });
  };
  return (
    <div className="container mt-5">
      <div className="col-5">
        <h3 style={{ textAlign: "center",color:'blue' }}>Employee List</h3>
        <table className="table table-striped table-hover">
          <thead>
            <tr>
              <th>EMP ID</th>
              <th>NAME</th>
              <th>SALARY</th>
              <th>D O B</th>
              <th>ACTION</th>
            </tr>
          </thead>
          <tbody>
            {employees.map((e) => {
              return (
                <tr key={e.empid}>
                  <td>{e.empid}</td>
                  <td>{e.name}</td>
                  <td>{e.salary}</td>
                  <td>{e.dob.toLocaleString("en-GB")}</td>
                  <td>
                    <button
                      className="btn btn-danger"
                      onClick={() => deleteData(e.empid)}
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
        {message != "" ? <p className='alert alert-success'>{message}</p> : null}
      </div>
    </div>
  );
};

export default EmpList;
