// emp-routing/src/app/emp-update/emp-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { EmployeeDataService } from 'src/employee-data.service';
import { Employee } from 'src/model/employee';

@Component({
  selector: 'app-emp-update',
  templateUrl: './emp-update.component.html',
  styleUrls: ['./emp-update.component.css'],
})
export class EmpUpdateComponent implements OnInit {
  emp: Employee = { empId: 0, name: '', salary: 0, gender: '' };
  message = '';
  constructor(
    private service: EmployeeDataService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.route.paramMap.subscribe((params) => {
      let eidstr: string | null = params.get('empid');
      if (eidstr == null) {
      } else {
        let eid = parseInt(eidstr);
        this.service.getEmployee(eid).then(
          (data) => (this.emp = { ...data }),
          (msg) => {
            this.message = msg;
            setTimeout(() => {
              this.router.navigate(['/emplist']);
            }, 5000);
          }
        );
      }
    });
  }

  saveData(){
    this.message = this.service.updateEmployee(this.emp);
    setTimeout(() => {
      this.router.navigate(['/empdetails',this.emp.empId]);
      
    }, 5000);
  }
}

<div class="container m-5">
    <h5 class='text-center'>Modify Employee</h5>
    
    <div class="form-group">
      <label>Employee Id</label>
      <input
        [(ngModel)]="emp.empId"
        class="form-control"
        readonly >
    </div>
  
  <div class="form-group">
    <label>Name</label>
    <input
      [(ngModel)]="emp.name"
      class="form-control"
    />
  </div>

  <div class="form-group">
    <label>Salary</label>
    <input
      type="number"
     [(ngModel)]="emp.salary"
      class="form-control"
    />
  </div>

  <div class="form-group">
    <label>Gender</label>
    <input
      [(ngModel)]="emp.gender"
      class="form-control"
    />
  </div>

  <div class="d-grid gap-2">
    <button  class="btn btn-outline-primary" (click)="saveData()" > Save Data   </button>
  </div>

<div *ngIf="message != ''" class="alert alert-info p-0">{{ message }}</div>
</div>

// components/emp-update.tsx
import axios from "axios";
import { ChangeEvent, useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import Employee from "../model/employee";


const EmpUpdate = ( ) => {
  const [emp, setEmp] = useState<Employee>({
    empid: 0,
    name: "",
    salary: 0,
    dob: new Date(),
  });
  const [message, setMessage] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(true);
  const [dataFound,setDataFound] =  useState(false);

  let navigate=useNavigate()

  let params=useParams();

  useEffect(() => {
    let url = `http://localhost:8080/employees/${params.empid}`;
    axios.get(url).then(
      (response) => {
        setEmp(response.data);
        setLoading(false);
        setDataFound(true)
      },
      (error) => {
        setMessage(error.response.data.message);
        setLoading(false);
      }
    );
  }, []);

  let handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    let name = e.target.name;
    let value = e.target.value;
    switch(name){
        case 'name': emp[name]=value; break;
        case 'salary': emp[name]=parseFloat(value); break;
        case 'dob': emp[name] = new Date(value);
    }
  };

  let saveData=()=>{
      axios.put("http://localhost:8080/employees",emp)
      .then(
          (response)=>{ 
            setMessage(response.data.message);
            setTimeout(() => {
              navigate("/emplist")
            }, 5000);
          },
          (error)=>{ 
            setMessage(error.response.data.message);
            setTimeout(() => {
              navigate("/emplist")
            }, 5000);
           }
      )
  }

  if (loading) {
    return <h4>loading .....</h4>;
  }

  if(dataFound){
  return (
    <div>
      <h3>Modify Employee</h3>

      <div className="form-group">
        Employee Id:
        <input
          type="number"
          className="form-control"
          name="empid"
          defaultValue={emp.empid}
          readOnly
        />
      </div>
      <div className="form-group">
        Name:
        <input
          className="form-control"
          name="name"
          defaultValue={emp.name}
          onChange={handleChange}
        />
      </div>
      <div className="form-group">
        Salary:
        <input
          type="number"
          className="form-control"
          name="salary"
          defaultValue={emp.salary}
          onChange={handleChange}
        />
      </div>
      <div className="form-group">
        Date of Birth:
        <input
          type="date"
          className="form-control"
          name="dob"
          defaultValue={emp.dob.toLocaleString()}
          onChange={handleChange}
        />
      </div>
      <div>
        <button className="btn btn-success" onClick={saveData} >Save</button>
        <button className="btn btn-danger" onClick={ ()=>{navigate('/emplist')} }>Cancel</button>
      </div>
      {message != ""? <p className='alert alert-success'>{message} </p>:null}
    </div>
  );
  }
  else{
    return (<div>{message}</div>)
  }
};

export default EmpUpdate;
