// routing-app/src/app/emp-create/emp-create.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core";
import { FormControl, FormGroup } from "@angular/forms";
import { Employee } from "../model/employee";
import { EmpService } from "../services/emp.service";

@Component({
  selector: "emp-create",
  templateUrl: "./emp-create.component.html",
  styleUrls: ["./emp-create.component.css"],
})
export class EmpCreateComponent {
  @Output() close = new EventEmitter();

  constructor(private service: EmpService) {}

  success:boolean
  message: string = null;
  validationMessages: string[];
  saveData(emp: Employee) {
    this.service.saveEmployee(emp).subscribe(
     (result) =>{
      this.message = result.message;
      this.success = true;
    },
    (errorResponse)=> {
      this.message = errorResponse.error.errorMessage
      this.success = false;
    }
    );
  }
  
}

<p style="text-align: center">Create New Employee Data</p>

<form #empForm="ngForm" (submit)="saveData(empForm.value)">
  Emp Id:
  <input
    class="form-control"
    ngModel
    name="empid"
    #tempId="ngModel"
    required
    pattern="[1-9][0-9]{2}"
  />
  <div *ngIf="tempId.touched && tempId.invalid">
    <div *ngIf="tempId.errors.required" class="alert alert-danger">
      Employee Id is required
    </div>
    <div *ngIf="tempId.errors.pattern" class="alert alert-danger">
      Employee Id should be 3 numeric digits(first digt non-zero)
    </div>
  </div>
  Name:
  <input
    class="form-control"
    ngModel
    name="name"
    #tname="ngModel"
    required
    minlength="5"
  />

  Salary:
  <input
    type="number"
    class="form-control"
    ngModel
    name="salary"
    #tsalary="ngModel"
    required
    min="10000"
  />
  <div *ngIf="tsalary.touched && tsalary.invalid">
    <div *ngIf="tsalary.errors.required" class="alert alert-danger">
      Salary field cannot be empty
    </div>
    <div *ngIf="tsalary.errors.minlength" class="alert alert-danger">
      Salary should be minimum 10000
    </div>
  </div>

  <div>
    <button
      class="btn btn-primary btn-block"
      type="submit"
      [disabled]="empForm.invalid"
    >
      Save
    </button>
  </div>
</form>
<p
  *ngIf="message != null" (click)="message = null"  [ngClass]="success ? 'alert alert-success' : 'alert alert-danger'">
  {{ message }}
</p>

<div *ngIf="validationMessages" (click)="validationMessages = null">
  <p *ngFor="let message of validationMessages">{{ message }}</p>
</div>

// emp-react-app-code/src/components/emp-create.tsx
import axios from "axios";
import React from "react";
import { useState } from "react";
import { useForm} from "react-hook-form";
import { Employee } from "../employee";


export  const EmpCreate = () => {
  const [message, setMessage] = useState("");

  const {
    register,
    handleSubmit,
    reset,
    formState:{errors},
  } = useForm<Employee>();

  const onSubmit = (data: Employee) => {
   // console.log("data", data);

    axios
    .post("http://localhost:8080/employees",data)
    .then((response) => {
      setMessage(response.data.message)
    })
    .catch((error) => {
      setMessage(error.response.data.message);
    });
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <div className="container">
        <h3 className="header"> create Employee</h3>

        <div className="form-group">
          <label htmlFor="empid">Emp Id</label>
          <input
            id="empid"
            className="form-control"
            {...register("empid", { required: true, pattern: /[1-9][0-9]{2}/ })}
          />
        </div>

        {errors.empid && errors.empid.type === "required" ? (
          <div className="text-danger">Employee Id is required</div>
        ) : null}

        {errors.empid && errors.empid.type === "pattern" ? (
          <div className="text-danger">Exact 3 digits and first non-zero</div>
        ) : null}

        <div className="form-group">
          <label htmlFor="name">Name</label>
          <input
            id="name"
            className="form-control"
            {...register("name", { required: true, minLength: 3 })}
          />
        </div>
        {errors.name && errors.name.type === "required" ? (
          <div className="text-danger">Name is required</div>
        ) : null}
        {errors.name && errors.name.type === "minLength" ? (
          <div className="text-danger">Name should be minimum 3 chars</div>
        ) : null}
        <div className="form-group">
          <label htmlFor="salary">Salary </label>
          <input
            id="salary"
            className="form-control"
            {...register("salary", { required: true, min: 10000 })}
          />
        </div>
        {errors.salary && errors.salary.type === "required" ? (
          <div className="text-danger">Salary is required</div>
        ) : null}
        {errors.salary && errors.salary.type === "min" ? (
          <div className="text-danger">Minimum salary 10000</div>
        ) : null}
        <div className="form-group">
          <label htmlFor="dob">D O B</label>
          <input
            type="date"
            id="dob"
            className="form-control"
            {...register("dob", { required: true })}
          />
        </div>
        {errors.dob && errors.dob.type === "required" ? (
          <div className="text-danger">DOB is required</div>
        ) : null}
        <div className="d-grid gap-2">
          <button className='btn btn-primary'  type="submit" >
            Save
          </button>
          <button className="btn btn-danger" onClick={()=>reset()}>
            Clear Form
          </button>
        </div>
        {message!=='' && (<div>{message}</div>)}
      </div>
    </form>
  );
};
