// routing-app/src/app/emp-list/emp-list.component.ts
import { HttpClient } from "@angular/common/http";
import { Component, OnInit } from "@angular/core";
import { Observable } from "rxjs";
import { Employee } from "../model/employee";
import { EmpService } from "../services/emp.service";

@Component({
  selector: "emp-list",
  templateUrl: "./emp-list.component.html",
  styleUrls: ["./emp-list.component.css"],
})
export class EmpListComponent implements OnInit {
  constructor(private service: EmpService) {}

  ngOnInit(): void {
    this.loadData();
  }

  employees: Employee[];

  message: string = null;

  delete(empid: number) {
    this.service.deleteEmployee(empid).subscribe(
      (resp) => {
        this.loadData();
        this.message = resp.message;
      },
      (response) => {
        this.message=response.error.errorMessage;
      }
    );
  }


  loadData() {
    this.service.getAllEmployees().subscribe(
      (data) => (this.employees = data),
      (response) => (this.message = response.error.errorMessage)
    );
  }
}

<div  class='container'>
  
    <h3 style="text-align: center">Employee List</h3>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>EMP ID</th>
          <th>NAME</th>
          <th>SALARY</th>
          <th>ACTION</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let e of employees">
          <td>{{ e.empid }}</td>
          <td>{{ e.name }}</td>
          <td>{{ e.salary}}</td>
          <td class='btn-group'>
            <a [routerLink]="['/update',e.empid]" class='btn btn-outline-primary mr-2'>Update</a>
            <button class="btn btn-outline-danger" (click)="delete(e.empid)" >Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
    <p *ngIf="message" class="alert alert-danger"  (click)="message = null" >
      {{ message }}
    </p>
 
  </div>

// emp-react-app-code/src/components/emp-list.tsx
import { Alert, Button, Container, Table } from "react-bootstrap";
import { useEffect, useState } from "react";
import { Employee } from "../employee";


import axios from "axios";
import { Link } from "react-router-dom";
import { getTsBuildInfoEmitOutputFilePath } from "typescript";

export function EmpList() {

    const [message, setMessage] = useState<string>("");
    const [employees, setEmployees] = useState<Employee[]>([]);
  
    useEffect(() => loadData(),[]);
  
    // functions for operations
  
    let deleteData = (empid: number) => {
      axios.delete(`http://localhost:8080/employees/${empid}`)
        .then((resp) => {
          loadData();
          setMessage(resp.data.message);
        })
        .catch((error) => {
          setMessage(error.response.data.message);
        })
    }
    

    let loadData = () => {
      axios
        .get("http://localhost:8080/employees")
        .then((response) => {
          setEmployees(response.data);
        //  console.log(employees)
        })
        .catch((error) => {
          setMessage(error.response.data.message);
        });
    };
    return (
        <div >
          <h3 style={{ textAlign: "center" }}>List of Employees</h3>
  
          <Table striped bordered hover>
            <thead>
              <tr>
                <th>EMP ID</th>
                <th>NAME</th>
                <th>SALARY</th>
                <th>DOB</th>
                <th>ACTION</th>
              </tr>
            </thead>
            <tbody>
              {employees.map((emp, i) => (
                <tr key={i}>
                  <td>{emp.empid}</td>
                  <td>{emp.name}</td>
                  <td>{emp.salary}</td>
                  <td>{emp.dob}</td>
  
                  <td>
                    <Button  variant="danger"
                      onClick={() => deleteData(emp.empid)}
                    >
                      Delete
                    </Button>
                    <Link
                     to={`/empupdate/${emp.empid}`}  className='btn btn-success'                >
                      Modify
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
          
          {message != "" ? (
            <Alert variant="danger" onClick={() => setMessage("")}>
              {message}
            </Alert>
          ) : null}
        </div>
       
    );
  }
